### PR TITLE
add footer html and footer scss

### PR DESCRIPTION
**Pull request by MaksymDranovskyi**

### CODE REVIEW

**Review by cheptsova — CHANGES_REQUESTED** [review]
fix

**Review by cheptsova — CHANGES_REQUESTED** [review]
fix

**Comment by cheptsova** [comment]
fix

**Review by cheptsova — CHANGES_REQUESTED** [review]
fix

**Review by cheptsova — COMMENTED** [review]
fix

**Review by cheptsova — CHANGES_REQUESTED** [review]
fix

**Comment by MaksymDranovskyi** [comment]
fix conflict

**Review by cheptsova — CHANGES_REQUESTED** [review]
ок

**Pull request closed without merging**
